### PR TITLE
fix: stopped recalculation when no value change; fixed debounce on input

### LINKED ISSUE #365: Avoid recalculating when coin input value don't change
When we keep typing more than our decimal limit, swap value is recalculated every time

**Expected Result**
Swap preview value should not be recalculated when value don't change

https://user-images.githubusercontent.com/8636507/177416216-6775f267-8d8a-4940-b623-cef5780921bf.mov

### LINKED ISSUE #368: Requests are being fired every 600ms, even if user still typing
**Expected Result**
- Requests should not be fired until debounce is completed

**Actual Behavior**
- Requests are being fired every 600ms, even if user still typing

https://user-images.githubusercontent.com/8636507/177681109-7a97ebce-824d-4490-9e85-7f39648336c2.mov

### PR DESCRIPTION
**Pull request by nedsalk**
There are some failing tests in SwapPage.Test.tsx but they are failing on master. No additional regressions have been introduced in this branch.

closes #365; closes #368.

### CODE REVIEW

File: packages/app/src/systems/Core/components/CoinInput.tsx [hunk 1]
```diff
@@ -77,3 +63,43 @@ export const CoinInput = forwardRef<HTMLInputElement, CoinInputProps>(
...
+  }, [value]);
+
+  useEffect(() => {
+    if (parseFloat(value) === 0 && initialValue === ZERO_AMOUNT.value) return;
+    setValue(initialValue);
+  }, [initialValue]);
+
+  const valueSetter = useCallback(
+    (e: React.ChangeEvent<HTMLInputElement>) => {
+      if (e.currentTarget.value.startsWith(".")) {
```
Comment (luizstacio) [inline packages/app/src/systems/Core/components/CoinInput.tsx:84]: I think we could move this code to a function, it helps to make the code cleaner.

File: packages/app/src/systems/Core/components/CoinInput.tsx [hunk 2]
```diff
@@ -77,3 +63,43 @@ export const CoinInput = forwardRef<HTMLInputElement, CoinInputProps>(
...
+        setValue("0.");
+        return;
+      }
+
+      const hasLeadingZeros = e.currentTarget.value.match(/^0+\d/) != null;
+
+      if (hasLeadingZeros) {
+        const valueWithoutLeadingZeros = parseFloat(
```
Comment (luizstacio) [inline packages/app/src/systems/Core/components/CoinInput.tsx:92]: I think you can clean up the leading zeros direct by using the replace string. No need to parse to float as you already run a regex to check.

**Review by luizstacio — CHANGES_REQUESTED** [review]
Thanks for the contribution; sorry for the delay in getting it reviewed!

Some minor requests, please provide feedback if you don't agree. Thanks

File: packages/app/src/systems/Core/components/CoinInput.tsx (hunk 1 above)
Comment (nedsalk) [reply packages/app/src/systems/Core/components/CoinInput.tsx]: Please take a look at the new implementation. `useDisplayedCoins` is a helper hook that encapsulates value getting/setting and IMO the function in `valueSetter`'s `useCallback` hook is small, straightforward enough, and directly tied to `useDisplayedCoins` so much that separating it out would bring too much indirection for my taste.

**Review by LuizAsFight — CHANGES_REQUESTED** [review]
I runned your PR in my computer. Your code changes make sense, but functionally saying, the issues you mentioned to close are not fixed.

Let me know if you need more clarifications in the issues

**Comment by nedsalk** [comment]
@LuizAsFight Weird. Please try it on this latest [preview](https://swayswap-j8e2q6sjr-fuel-labs.vercel.app/swap?from=ETH&to=DAI) deployed on Vercel. Open up the dev tools' network tab and retry everything you did in the linked issues. 

Related to #368, the debounce works correctly in that 600ms after the last input, 8 graphql requests get sent. Previously there was no debouncing, there was only a 600ms delay between each value change and its 8 graphql requests being fired, so every value change triggered requests.

Related to #365, inputting additional values after the decimal unit limit now doesn't send any requests because of the `notValueChanged` guard preceding the `setInputValue` actions.

File: packages/app/src/systems/Swap/machines/swapMachine.ts [hunk 3]
```diff
@@ -445,8 +454,18 @@ export const swapMachine =
...
-          return !val.length || val === '0';
+          const val = parseFloat(ev.data.value);
+          return Number.isNaN(val) || val === 0;
+        },
+        notValueChanged: (ctx, ev) => {
+          const isFrom = ctx.direction === FROM_TO;
+          const next = createAmount(ev.data.value);
+
+          const valueChanged = isFrom
+            ? ctx.fromAmount == null || parseFloat(ctx.fromAmount.value) !== parseFloat(next.value)
```
Comment (luizstacio) [inline packages/app/src/systems/Swap/machines/swapMachine.ts:465]: Do we need the parseFloat here? We should avoid using `parseFloat`. If you really need to convert to a number first you can do this by using: [`parseUnits`](https://github.com/FuelLabs/swayswap/blob/dac9a7520d3679d169a302d4d1f2cb2b0b7d44c0/packages/app/src/systems/Core/utils/math.ts#L29).

Sorry didn't notice that before.

**Review by luizstacio — CHANGES_REQUESTED** [review]

**Comment by luizstacio** [comment]
> I runned your PR in my computer. Your code changes make sense, but functionally saying, the issues you mentioned to close are not fixed.
> 
> Let me know if you need more clarifications in the issues

I tested on the preview PR and it was working correctly maybe, you have another way to simulate to post here?

File: packages/app/src/systems/Swap/machines/swapMachine.ts (hunk 3 above)
Comment (nedsalk) [reply packages/app/src/systems/Swap/machines/swapMachine.ts]: Given that `parseUnits` returns a `BigInt`, I used the raw value of `CoinAmount`, which gets created via [`createAmount`](https://github.com/FuelLabs/swayswap/blob/652c83b3c09dde48f7f4f4c6aebce7ba88126d1e/packages/app/src/systems/Swap/utils/helpers.ts#L32), for equality comparison.

File: packages/app/src/systems/Core/components/CoinInput.tsx [hunk 4]
```diff
@@ -77,3 +62,36 @@ export const CoinInput = forwardRef<HTMLInputElement, CoinInputProps>(
     );
   }
 );
+
+function useDisplayedCoins(
```
Comment (LuizAsFight) [inline packages/app/src/systems/Core/components/CoinInput.tsx:66]: Instead of creating a new hook, I think this hook changes should go inside already existing `useCoinInput` hook, as which is the responsible for managing CoinInput.

**Review by LuizAsFight — CHANGES_REQUESTED** [review]

File: packages/app/src/systems/Core/components/CoinInput.tsx (hunk 4 above)
Comment (nedsalk) [reply packages/app/src/systems/Core/components/CoinInput.tsx:66]: The proposal makes sense, but unfortunately `useCoinInput` is not being used in any functionality related to swapping (the swap widget has its own `useSwapCoinInput` hook which doesn't reference `useCoinInput`), so there'd have to be some additional refactoring going on that's IMO out of scope for these two issues. This would I think better be done in a separate issue that's related to #306. I'd be happy to do it, but I believe it's worth a separate issue.

Comment (LuizAsFight) [reply packages/app/src/systems/Core/components/CoinInput.tsx:66]: yeah it would need to be implemented both in `useCoinInput` and `useSwapCoinInput`, we can refact it in other issue.

1- For now then we should move this hook to `hooks` folder, instead of living inside `CoinInput` component. Suggestion for name is `useCoinInputDisplayValue`
2- We have a broken test related to coin input value in other page, which may be a side effect. Do you know why the test is broke? We cannot merge it with broken tests so we may either fix it or if it's a false alert skip the test and create a new issue to fix it later

Comment (nedsalk) [reply packages/app/src/systems/Core/components/CoinInput.tsx]: 1- Done.
2- I fixed it. The hook was using `e.currentTarget.value` whereas the test was firing a change event with a `target` object.

**Comment by nedsalk** [comment]
@LuizAsFight The failing test succeeds when I run it alone via vscode's jest plugin, but it fails when I do pnpm test (run all tests together). I didn't investigate much and skipped the test because this functionality should be covered as part of #306. Is that ok with you?

**Review by LuizAsFight — APPROVED** [review]
LGTM. 

@nedsalk thanks for you contribution!


cc @luizstacio

**Review by luizstacio — APPROVED** [review]
