### PR TITLE
fix(PoolPage): improve add_liquidity contract

### LINKED ISSUE #200: Create pool with incorrect ratio makes you lose your balance and throws only raw string error
**Obs.**
1- #141 will address a general feedback and handle it in front-end, but we still need to fix the `lost balance` problem and a nice error do show specific feedback
2- This is not an error that can be reproduced in prod env. Needs to skip validations in code to get to it.

**How to reproduce**
1- comment out ratio validations in `PoolPage` -> `Add Liquidity`
2- create a NEW pool: `0.1 ETH <-> 100 DAI`
3- add liquidity with less DAI than the right ratio: `0.1 ETH <-> 10 DAI`

**Problem**
1- User lose balance when this error happen
2- Error is just a string in this case, not able to identify what is the specific problem

**Objective**
1- User cannot lose balance when this goes wrong, need to revert the deposit transactions.
2- Get a nice error to be able to show a specific feedback about what happened to the user

Error example:
`'Script returned non-zero result: 1\n\nReverts:\n0xad3134370511cecb84064622a87b6f7472e7d6423b8e9ea13753bed4c58fc1c2: {"val":"0","pc":"18356","is":"11976"}\n0xad3134370511cecb84064622a87b6f7472e7d6423b8e9ea13753bed4c58fc1c2: {"val":"0","pc":"18356","is":"11976"}\n\nReceipts:\n[\n  {\n    "type": "Call",\n    "from": "0xad3134370511cecb84064622a87b6f7472e7d6423b8e9ea13753bed4c58fc1c2",\n    "to": "0xad3134370511cecb84064622a87b6f7472e7d6423b8e9ea13753bed4c58fc1c2",\n    "amount": "0",\n    "assetId": "0x0000000000000000000000000000000000000000000000000000000000000000",\n    "gas": "999515",\n    "param1": "2237385406",\n    "param2": "10696",\n    "pc": "11976",\n    "is": "11976"\n  },\n  {\n    "type": "Revert",\n    "id": "0xad3134370511cecb84064622a87b6f7472e7d6423b8e9ea13753bed4c58fc1c2",\n    "val": "0",\n    "pc": "18356",\n    "is": "11976"\n  },\n  {\n    "type": "Revert",\n    "id": "0xad3134370511cecb84064622a87b6f7472e7d6423b8e9ea13753bed4c58fc1c2",\n    "val": "0",\n    "pc": "18356",\n    "is": "11976"\n  },\n  {\n    "type": "ScriptResult",\n    "result": "1",\n    "gasUsed": "17076"\n  }\n]'`

### PR DESCRIPTION
**Pull request by LuizAsFight**
- contract changes
  - add_liquidity
    - use always contract user balance, instead of front-end value
    - if tokens ratio is wrong, contract won't break anymore. Instead we return the previous depositted user balances to his wallet
    - if tokens ratio is ok, should return any leftover token to user wallet
  - get_balance
    - return user contract balance, instead of whole contract balance

- frontend changes
  - PoolPage - Add Liquidity - removed ratio validation from front-end, as contract is already handling it now
  - increased deadline to 5000 in remove_liquidity and add_liquidity
  - created config param for contracts Deadline

Closes #200

### CODE REVIEW

File: packages/app/src/pages/PoolPage/index.tsx [hunk 1]
```diff
@@ -1,35 +1,12 @@
...
+import { Outlet } from "react-router-dom";
 
-import { Button } from "~/components/Button";
 import { Card } from "~/components/Card";
 
-const style = {
-  button: `relative font-semibold text-xs`,
-};
-
-const SubpagesNav = () => {
```
Comment (luizstacio) [inline packages/app/src/pages/PoolPage/index.tsx:12]: This needs to 
be a conditional thing, just removing makes impossible to arrive at the add liquidity page;

Screen Shot 2022-05-25 at 8 41 57 PM

**Review by luizstacio — CHANGES_REQUESTED** [review]

**Review by luizstacio — APPROVED** [review]
LGTM!
